spring.application.name: api-gateway
server.port: 8080

# Enregistrement Eureka
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true
eureka.instance.hostname: localhost

# Actuator pour le monitoring
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: school-service
          uri: lb://school-service
          predicates:
            - Path=/api/schools/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**